
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/qp/qtools/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Windows -  - x86_64
      The host system is: Windows - 10.0.26200 - AMD64
...
